---
dependency:
  name: galaxy
  requirements_file: requirements.yml
driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint
platforms:
  - name: instance-1
    box: centos/7
    memory: 1024
    cpus: 2
    interfaces:
      - auto_config: true
        network_name: private_network
        type: static
        ip: 192.168.11.3
  - name: instance-2
    box: ubuntu/bionic64
    memory: 1024
    cpus: 2
    interfaces:
      - auto_config: true
        network_name: private_network
        type: static
        ip: 192.168.11.4
provisioner:
  name: ansible
  playbooks:
    converge: ../../playbook.yml
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
